export const INCREMENT = "INCREMENT";

export const DELETE_ARTICLE = "DELETE_ARTICLE";

export const SET_FILTERS_START_DATE = "SET_FILTERS_START_DATE";
export const SET_FILTERS_END_DATE = "SET_FILTERS_END_DATE";
